language: node_js

node_js:
  - node

before_script:
  - yarn

jobs:
  include:
    - stage: test
      script: yarn lint
    - stage: release
      script: yarn release
      if: branch = master

stages:
  - test
  - name: release
    if: branch = master
